#!/usr/bin/env bash
CONFLICTS=$(git diff --name-only --diff-filter=U | grep -F .secret)
if [ -n "$CONFLICTS" ]; then
  START_DIR=$PWD
  cd $(git rev-parse --show-toplevel)
  : "${SECRETS_EXTENSION:=".secret"}"
  for SECRET_CONFLICT in $CONFLICTS; do
    THEIRS_TMP=$(mktemp)
    OURS=$(dirname $SECRET_CONFLICT)/$(basename $SECRET_CONFLICT $SECRETS_EXTENSION)
    git checkout --theirs $SECRET_CONFLICT
    gpg --output $THEIRS_TMP --quiet --yes --decrypt $SECRET_CONFLICT
    git merge-file $OURS /dev/null $THEIRS_TMP
    rm ${THEIRS_TMP}
    echo "Merge conflict exported to $OURS"
  done
  if [ $1 = "-i" ]; then
     read -p "Fix conflicts and press any key to continue..."
     git secret hide -m
  else
    echo "Fix conflicts and hide them, then continue with the merge"
  fi
  cd $START_DIR
fi